G01_主食:
  Category:
  - 大米
  - 挂面
  - 方便面
  - 面粉
  weight:
  - 0.5713783
  - 0.0991645
  - 0.1851895
  - 0.1442678
G02_食用油:
  Category: 食用油
  weight: 1.0
G03_蔬菜:
  Category: 蔬菜
  weight: 1.0
G04_水果:
  Category: 水果
  weight: 1.0
G05_猪肉:
  Category: 猪肉
  weight: 1.0
G06_禽类及其他肉类:
  Category:
  - 其他肉类
  - 禽类
  weight:
  - 0.049768
  - 0.950232
G07_牛羊肉:
  Category:
  - 牛肉
  - 羊肉
  weight:
  - 0.7505952
  - 0.2494048
G08_海鲜:
  Category: 海鲜类
  weight: 1.0
G09_乳制品:
  Category:
  - 奶酪
  - 常温牛奶
  - 常温酸奶
  - 成人奶粉
  - 新鲜牛奶
  - 新鲜酸奶
  - 黄油
  weight:
  - 0.0136315
  - 0.4082131
  - 0.2247102
  - 0.1163475
  - 0.0445813
  - 0.1382298
  - 0.0542866
G10_坚果:
  Category: 坚果
  weight: 1.0
